### ISSUE TITLE
OSM SkillEntry.requirements is list not dict

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos_skill_manager#25]
When parsing a skill with requirements.txt, `SkillEntry._data["requirements"] = {list_parsed_from_requirements_txt}`. At install, `self.requirements` is expected to be a dict of "python", "skill", "system" dependencies.

Few considerations here:
* It appears that `requirements.txt` is overriding the `skill.json`. In general, should repo files take priority over `skill.json`?

* `requirements.txt` is superseded by `requirements.yml`, should we handle cases where both of these exist? How do these interact with `skill.json`?

**Comment by JarbasAl** [comment]
the skill.json should always take precedence, however if missing then the json is generated automatically and parses repo files, do we want to augment the json or only generate it? i think augmenting is good, one less file for devs to maintain, but we should never overwrite a value already defined

we want to support requirements.txt since it is officially supported by mycroft and very common, i personally tend to use that and ignore the manifest.yml. If both exist then manifest.yml should take precedence over requirements.txt

**Comment by NeonDaniel** [comment]
Okay, so for reference when we address this properly, we should load in priority order:
* skill.json
* manifest.yml
* requirements.txt

>>>if missing then the json is generated automatically and parses repo files, do we want to augment the json or only generate it?
Are you saying we should update skill.json with requirements if not defined? Not sure I follow

**Comment by ChanceNCounter** [comment]
2¢: `if thing not in` should get through setup without the need to augment skill.json

**Comment by JarbasAl** [comment]
> Are you saying we should update skill.json with requirements if not defined? Not sure I follow

Yes, if skill.json exists and does not have requirements defined inside and requirements.txt/manifest.yml exist, then those should augment the json


- if skill.json contains requirements
- if manifest.yml exists
- if requirements.txt exists

**Comment by JarbasAl** [comment]
> 2¢: `if thing not in` should get through setup without the need to augment skill.json

keep in mind that we build a local cache with all info about skills, this allows things like searching the appstores without reaching out to the internet (thats why sync command is a thing), so its not only about failing the install

**Comment by ChanceNCounter** [comment]
> keep in mind that we build a local cache with all info about skills, this allows things like searching the appstores without reaching out to the internet (thats why sync command is a thing), so its not only about failing the install
> 
Makes sense. Should it rebuild itself on skill update? If not, we also need to put some thought into the git pull problem.

**Comment by NeonDaniel** [comment]
Current behavior is to update on some appstore_sync interval, right? Rebuilding permissions could happen there (or on manual updates)

**Comment by NeonDaniel** [comment]
>Yes, if skill.json exists and does not have requirements defined inside and requirements.txt/manifest.yml exist, then those should augment the json

This is just for the local cache, right? I don't know that we want to try updating repo files

**Comment by JarbasAl** [comment]
only update in local cache yes, OSM does not send anything anywhere, just retrieves stuff

skill update should rebuild the entry since it's as good time as any, since we got the data let's process it!

**Comment by NeonDaniel** [comment]
A few notes regarding private git dependencies that came up. Given: `requirement @ git+https://github.com/org/repo@branch`
* `branch` is case sensitive
* the rest of the url is case sensitive for PIP conflict checks (best option IMO is always lowercase it)
* for skills with auth, there could be dependencies with auth requirements too; I have an example [here](https://github.com/NeonDaniel/neon-test-utils/blob/0873dbe44e8d30c34fc680efde8ee895fb3719f5/setup.py#L24)
* invalid auth is apparently ignored in pip if the repo is public/auth isn't required

**Comment by NeonDaniel** [comment]
> * if skill.json contains requirements
> * if manifest.yml exists
> * if requirements.txt exists

Thoughts on version conflicts? My inclination is to take the latest version; for my workflow (and I imagine Mycroft skill devs), I am more likely to update requirements/manifest before I update skill.json...

**Comment by JarbasAl** [comment]
I'm not sure there is a right choice here, I'm inclined to agree with you, let's account for the most common use case

in appstores we should confirm that all of these match so it is not an issue, that leaves out developer/power user convenience

**Comment by NeonDaniel** [comment]
regarding system dependencies, the `manifest.yml` scheme is that this is a string that would be passed to `apt`, etc. Should `skill.json` be the same, or should it be a list? Either way, I think it needs to be parsed into a list internally to handle merging requirements

**Comment by JarbasAl** [comment]
i think we want that to be a list

**Comment by NeonDaniel** [comment]
> i think we want that to be a list

I was just going to say this is going to be pretty ugly if I have to parse a string to a list in here

**Comment by JarbasAl** [comment]
feature, that is intended, think about version pinning

**Comment by NeonDaniel** [comment]
> feature, that is intended, think about version pinning

Just making sure. If no branch is spec'd, the json should come from the default branch, correct? Test repo I'm using will definitely not follow best practice, trying to catch unusual situations now.

**Comment by JarbasAl** [comment]
> If no branch is spec'd, the json should come from the default branch, correct? 

yes, im thinking is that the main branch will be the dev branch, but the json (if it exists) will reflect the branch of last stable release

**Comment by NeonDaniel** [comment]
Regarding dependency conflicts, I think that might be out of scope for this PR; for now, pip should handle finding compatible versions within all passed constraints and all constraints are handled here already. Edge case that currently isn't handled is if `skill.json`, `requirements.txt`, and `manifest.yml` contain version specs that are incompatible

**Comment by NeonDaniel** [comment]
Any ideas why OVOS bootstrap seems to return an empty list?

https://github.com/NeonDaniel/ovos_skill_manager/runs/2697290543?check_suite_focus=true
