### ISSUE TITLE
Find a free coverage bot and set it up

### ISSUE THREAD

**Issue by ChanceNCounter** [OpenVoiceOS/ovos_skill_manager#39]
I dunno where to host `pytest --cov`, or I'd just set that up myself right now.

**Comment by ChanceNCounter** [comment]
I have no idea how to vet Codecov, but it seems to be working for MycroftAI, and it's free for FOSS. Drops that nice little comment in the PR, no need to get coverage into an Action or store its output.

It does require access via a GitHub account with repo perms, so it would probably be best to set up some kind of devops GitHub account for the OVOS org, assuming the GitHub terms allow that. I know companies do it sometimes, but I don't know if you have to spend money to be allowed.

@NeonDaniel?

**Comment by NeonDaniel** [comment]
Iirc, GitHub allows bot accounts with some "be reasonable" caveats. I haven't looked at coverage, but actions generally don't require any special account and show up as a GitHub bot

**Comment by ChanceNCounter** [comment]
The one in question shows up in repos as itself, but it wants repo perms in order to do its work (and edit status lines.) I think it would be better if things like that got in through an OpenVoiceOS account, rather than one of our accounts, both so that things keep working if someone leaves the org and so that we can cut off its head in the event of an emergency.

**Comment by NeonDaniel** [comment]
> Iirc, GitHub allows bot accounts with some "be reasonable" caveats (okay for actions, other automation, etc.). I haven't looked at coverage, but actions generally don't require any special account and show up as a GitHub bot

Documentation referenced: https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts
> User accounts are intended for humans, but you can give one to a robot, such as a continuous integration bot, if necessary.

**Comment by ChanceNCounter** [comment]
God, I love these people. And I'm a GitLab expat.

**Comment by NeonDaniel** [comment]
Closed by #75
