### ISSUE TITLE
SkillEntry property types

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos_skill_manager#47]
Discussion regarding `SkillEntry` property default returns. I would propose updating properties  to always return a string, rather than Optional[str].

Pros:
* type checking is safe in unit tests and other methods
* avoids potential logging errors if a property is in an f-string
* if {property} checks not affected

Cons:
* Properties are less-directly tied to `SkillEntry.json`
* Potentially obfuscates errors when a property is missing from `json`
* Few more characters in property methods

**Comment by NeonDaniel** [comment]
Also note `appstore`, `skill_folder`, `skill_category`, `skill_icon`,  use default strings, `skill_folder` and `skill_author`, `branch_overrides`, and `license` do this already

**Comment by JarbasAl** [comment]
no objections
